[01/20/2025 10:52:10 PM:plugins.index:78:ERROR] Telegram says: [400 CHANNEL_PRIVATE] (caused by "channels.GetFullChannel") Pyrogram 2.3.45 thinks: The channel/supergroup is not accessible
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 72, in send_for_index
    await bot.get_chat(chat_id)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/chats/get_chat.py", line 83, in get_chat
    r = await self.invoke(raw.functions.channels.GetFullChannel(channel=peer))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: Telegram says: [400 CHANNEL_PRIVATE] (caused by "channels.GetFullChannel") Pyrogram 2.3.45 thinks: The channel/supergroup is not accessible
[01/20/2025 10:52:51 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 105, in send_for_index
    link = f"@{message.forward_from_chat.username}"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
[01/20/2025 10:52:57 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 105, in send_for_index
    link = f"@{message.forward_from_chat.username}"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
[01/20/2025 10:53:10 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 105, in send_for_index
    link = f"@{message.forward_from_chat.username}"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
[01/20/2025 10:53:22 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 105, in send_for_index
    link = f"@{message.forward_from_chat.username}"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
[01/20/2025 10:53:29 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 105, in send_for_index
    link = f"@{message.forward_from_chat.username}"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
[01/20/2025 10:54:05 PM:pyrogram.dispatcher:376:ERROR] Peer id invalid: 0
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 63, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/storage/sqlite_storage.py", line 210, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: 0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2692, in advantage_spell_chok
    reqstr = await client.get_users(reqstr1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/users/get_users.py", line 60, in get_users
    user_ids = await asyncio.gather(*[self.resolve_peer(i) for i in user_ids])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 91, in resolve_peer
    peer_type = utils.get_peer_type(peer_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/utils.py", line 327, in get_peer_type
    raise ValueError(f"Peer id invalid: {peer_id}")
ValueError: Peer id invalid: 0
[01/20/2025 10:55:15 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 371, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 1909, in cb_handler
    await client.edit_message_media(
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_media.py", line 299, in edit_message_media
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/20/2025 10:58:58 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 371, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/20/2025 11:00:26 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 1328, in cb_handler
    await query.answer(f"Hᴇʏ {query.from_user.first_name}, Tʜɪs Is Nᴏᴛ Yᴏᴜʀ Mᴏᴠɪᴇ Rᴇǫᴜᴇsᴛ. Rᴇǫᴜᴇsᴛ Yᴏᴜʀ's !", show_alert=True)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 171, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 74, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 1334, in cb_handler
    await query.answer(url=f"https://telegram.me/{temp.U_NAME}?start={ident}_{file_id}")
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 171, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 74, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
[01/20/2025 11:00:35 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 1328, in cb_handler
    await query.answer(f"Hᴇʏ {query.from_user.first_name}, Tʜɪs Is Nᴏᴛ Yᴏᴜʀ Mᴏᴠɪᴇ Rᴇǫᴜᴇsᴛ. Rᴇǫᴜᴇsᴛ Yᴏᴜʀ's !", show_alert=True)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 171, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 74, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 1334, in cb_handler
    await query.answer(url=f"https://telegram.me/{temp.U_NAME}?start={ident}_{file_id}")
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 171, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 74, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
[01/20/2025 11:03:01 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2491, in cb_handler
    await query.answer(MSG_ALRT)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 171, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 74, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
[01/20/2025 11:04:27 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/20/2025 11:04:27 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 371, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/commands.py", line 653, in start
    await k.edit_text("<b>Your File/Video is successfully deleted!!!\n\nClick below button to get your deleted file 👇</b>",reply_markup=InlineKeyboardMarkup(btn))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/20/2025 11:04:27 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 371, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/20/2025 11:04:27 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 371, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/20/2025 11:04:54 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 371, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2729, in advantage_spell_chok
    vj_ai_msg = await reply_msg.edit_text("<b><i>מנסה לחפש את החיפוש שלך עם איות שונה.</i></b>")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/20/2025 11:07:31 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 223, in next_page
    await query.answer()
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 171, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 74, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
[01/20/2025 11:08:14 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/commands.py", line 653, in start
    await k.edit_text("<b>Your File/Video is successfully deleted!!!\n\nClick below button to get your deleted file 👇</b>",reply_markup=InlineKeyboardMarkup(btn))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/20/2025 11:08:14 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/commands.py", line 653, in start
    await k.edit_text("<b>Your File/Video is successfully deleted!!!\n\nClick below button to get your deleted file 👇</b>",reply_markup=InlineKeyboardMarkup(btn))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/20/2025 11:10:54 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 223, in next_page
    await query.answer()
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 171, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 74, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] (caused by "messages.SetBotCallbackAnswer") Pyrogram 2.3.45 thinks: The callback query id is invalid
[01/20/2025 11:35:55 PM:pyrogram.dispatcher:376:ERROR] isinstance() arg 2 must be a type, a tuple of types, or a union
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/commands.py", line 660, in channel_info
    elif isinstance(CHANNELS, list):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
[01/20/2025 11:40:10 PM:plugins.index:78:ERROR] Telegram says: [400 CHANNEL_PRIVATE] (caused by "channels.GetFullChannel") Pyrogram 2.3.45 thinks: The channel/supergroup is not accessible
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 72, in send_for_index
    await bot.get_chat(chat_id)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/chats/get_chat.py", line 83, in get_chat
    r = await self.invoke(raw.functions.channels.GetFullChannel(channel=peer))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: Telegram says: [400 CHANNEL_PRIVATE] (caused by "channels.GetFullChannel") Pyrogram 2.3.45 thinks: The channel/supergroup is not accessible
[01/20/2025 11:40:37 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 105, in send_for_index
    link = f"@{message.forward_from_chat.username}"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
[01/20/2025 11:41:00 PM:plugins.index:78:ERROR] Telegram says: [400 CHANNEL_PRIVATE] (caused by "channels.GetFullChannel") Pyrogram 2.3.45 thinks: The channel/supergroup is not accessible
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 72, in send_for_index
    await bot.get_chat(chat_id)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/chats/get_chat.py", line 83, in get_chat
    r = await self.invoke(raw.functions.channels.GetFullChannel(channel=peer))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: Telegram says: [400 CHANNEL_PRIVATE] (caused by "channels.GetFullChannel") Pyrogram 2.3.45 thinks: The channel/supergroup is not accessible
[01/20/2025 11:41:40 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 105, in send_for_index
    link = f"@{message.forward_from_chat.username}"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
[01/20/2025 11:41:52 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'username'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/index.py", line 105, in send_for_index
    link = f"@{message.forward_from_chat.username}"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
[01/20/2025 11:42:38 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/20/2025 11:43:48 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 12:32:45 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 01:22:02 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 02:02:46 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 03:16:09 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 84, in pm_text
    await auto_filter(bot, content, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 04:04:10 AM:aiohttp.server:451:ERROR] Missing return statement on request handler
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 656, in finish_response
    prepare_meth = resp.prepare
                   ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'prepare'
[01/21/2025 10:30:17 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
[01/21/2025 10:51:30 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 11:03:11 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 11:19:06 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 11:19:42 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 11:20:51 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 11:32:01 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 11:32:27 AM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 01:24:56 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
[01/21/2025 01:25:37 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
[01/21/2025 01:25:45 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
[01/21/2025 02:24:08 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 02:26:57 PM:pyrogram.dispatcher:376:ERROR] 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2535, in auto_filter
    temp.SHORT[message.from_user.id] = message.chat.id
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[01/21/2025 02:35:40 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 254, in advantage_spoll_choker
    k = await query.message.edit(script.MVE_NT_FND)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/21/2025 02:45:04 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 05:06:42 PM:aiohttp.server:451:ERROR] Missing return statement on request handler
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 656, in finish_response
    prepare_meth = resp.prepare
                   ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'prepare'
[01/21/2025 05:06:42 PM:aiohttp.server:451:ERROR] Missing return statement on request handler
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 656, in finish_response
    prepare_meth = resp.prepare
                   ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'prepare'
[01/21/2025 05:54:30 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 05:55:06 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 05:55:20 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 05:55:35 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 05:55:57 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 05:56:39 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 05:57:26 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2720, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The button url is invalid
[01/21/2025 06:03:57 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 254, in advantage_spoll_choker
    k = await query.message.edit(script.MVE_NT_FND)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/21/2025 06:03:59 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 254, in advantage_spoll_choker
    k = await query.message.edit(script.MVE_NT_FND)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/21/2025 06:13:03 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 84, in pm_text
    await auto_filter(bot, content, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 06:14:40 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 84, in pm_text
    await auto_filter(bot, content, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 06:23:07 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 84, in pm_text
    await auto_filter(bot, content, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 07:32:39 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/callback_query_handler.py", line 207, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 254, in advantage_spoll_choker
    k = await query.message.edit(script.MVE_NT_FND)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message was not modified because you tried to edit it using the same content
[01/21/2025 07:34:13 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 07:35:56 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 07:36:22 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 07:42:28 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 07:43:01 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 07:50:15 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 84, in pm_text
    await auto_filter(bot, content, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 07:50:36 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 08:18:53 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 08:20:58 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 08:39:27 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
[01/21/2025 11:48:02 PM:pyrogram.dispatcher:376:ERROR] Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
Traceback (most recent call last):
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 58, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2520, in auto_filter
    return await advantage_spell_chok(client, name, msg, reply_msg, ai_search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/plugins/pm_filter.py", line 2746, in advantage_spell_chok
    k = await reply_msg.edit_text(text=script.I_CUDNT.format(mv_rqst), reply_markup=InlineKeyboardMarkup(button))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 4218, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/messages/edit_message_text.py", line 109, in edit_message_text
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/root/VJ-FILTER-BOT/myenv/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] (caused by "messages.EditMessage") Pyrogram 2.3.45 thinks: The message id is invalid
